name: PR Checker

permissions:
  contents: write
  pull-requests: write
  statuses: write 
  
on:
  pull_request:
    branches: [main]

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.paths.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in paths
        id: paths
        uses: dorny/paths-filter@v3.0.1
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'  

  frontend-build:
    if: ${{ needs.filter-changes.outputs.frontend_changed == 'true' }}
    needs: filter-changes
    name: Frontend Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache node modules  
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # npm ci is faster & deterministic
      - name: Install dependencies
        run: npm ci 

      - name: Run Build
        run: npm run build
      
      - name: Run prettier
        run: npm run format

      - name: Commit and push changes (Formatted Code)
        run: |
          git config --global user.name ${{github.actor}}
          git config --global user.email ${{github.event.pull_request.user.login}}
          git add .
          git diff --cached
          if git diff --cached --quiet; then
             echo "No changes to commit"
          else
            git commit -m "chore(frontend): apply prettier formatting"
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  backend-build:
    if: ${{ needs.filter-changes.outputs.backend_changed == 'true' }}
    needs: filter-changes
    name: Backend Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache node modules  
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      # npm ci is faster & deterministic
      - name: Install dependencies
        run: npm ci 

      - name: Run Build
        run: npm run build
      
      - name: Run prettier
        run: npm run format

      - name: Commit and push changes (Formatted Code)
        run: |
          git config --global user.name ${{github.actor}}
          git config --global user.email ${{github.event.pull_request.user.login}}
          git add .
          git diff --cached
          if git diff --cached --quiet; then
             echo "No changes to commit"
          else
            git commit -m "chore(backend): apply prettier formatting"
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}